# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
      
    # - run: |
         # sudo apt-get update
         # sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgbm1
         # sudo cp xvfb.init /etc/init.d/xvfb
         # sudo chmod +x /etc/init.d/xvfb
         # sudo update-rc.d xvfb defaults
         # sudo service xvfb start
    # - run: |
       # export DISPLAY=':99.0'
       # /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    
    - run: npm install
    - run: sudo npm install -g vsce
    - run: npm run tslint
    - run: npm run compile
    - run: node scripts/genAiKey.js
    - run: echo "y" | vsce package
    #- name: Run headless test
     # uses: GabrielBB/xvfb-action@v1
     # with: 
     #  run: npm test 
    - run: |
           export DISPLAY=':99.0'
           xvfb-run --auto-servernum --server-args="-screen 0, 1024x768x24" npm test --silent
           
  #- run: Xvfb :44 -auth /tmp/xvfb.auth -ac -screen 0 1920x1080x24 -nolisten tcp 
  #- run: npm test --silent

