publish:
   - name: Create GitHub Release
     id: publish 
     uses: actions/create-release@v1
     if: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
     env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
          repository: microsoft/vscode-azure-iot-edge
          tag_name: ${{Build.SourceBranch}}
          gitHubConnection: vikas0212git   
          target: ${{Build.SourceVersion}}
          tagSource: userSpecifiedTag
          changeLogCompareToRelease: lastFullRelease 
          cangeLogType: commitBased' 
   - name: Publish to Marketplace
     if: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
     with: 
         targetType: inline
         run: 'vsce publish -p $(VSCE_TOKEN) --packagePath *.vsix'
         workingDirectory: '$(Build.ArtifactStagingDirectory)'
